### ISSUE TITLE
Inconsistent behavior using env vars with '.' and '-'

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/libbuildpack#25] opened 2019-02-14 07:46 UTC
We are trying to chase down an intermittent issue that seems to be a combination of
* using the `cflinuxfs3` stack
* user-provided environment variables containing '.'s and '-'s like:
```
env.with.dot: something
env-with-dash: something
```
* Changes in the manifest (e.g. changing the start command) after first push

The result is that the above env vars do not show up in the process environment of the application. This is independent from the buildpack used and I was able to verify that indeed those variables are missing looking at `/proc/<pid>/environ` being `cf ssh`ed into the app.

Unfortunately, I so far wasn't able to narrow down the scenario to something that consistently works/fails, but here is the minimal app that I am using: https://gist.github.com/bkrannich/d77681d7ea5caf1b52a0ffda4fcfb6ff

Steps to (try and) reproduce:
* `cf push` the app
* Call it's URL in the browser
* Search for 'env.' or 'env-' - often times during initial `cf push` this is failing. Changing things like uncommenting the the `command` in `manifest.yml` and re-pushing sometimes changes the situation.

Additional observations:
* This issue doesn't seem to exist with `cflinuxfs2`.
* I have a hunch that it might be related to some conversion of YML to an intermediate format (BASH?) and/or back, but this does not explain why the issue is intermittent. Also, I found some places in https://github.com/cloudfoundry/libbuildpack/blob/master/stager.go as well as https://github.com/cloudfoundry/libbuildpack/blob/master/stager_unix.go#L14 that look suspicious in that respect, but modifying the stager_test.go, I wasn't able to provoke an error.

**Comment by sclevine** [comment] 2019-02-14 16:43
Hi @bkrannich,

libbuildpack is not involved in the processing of an app's manifest.yml, or the initial environment of the app container. This seems like an issue with the cf CLI or Cloud Controller.

It's worth noting that most shells do not support environment variables with `.` in them, even if the operating system does not impose this restriction.

**Comment by kardolus** [comment] 2019-02-19 15:07
Hi @bkrannich,

I wonder if this is an issue with `process.env`. When we checked the environment variables using `cf env <app_name>` or ssh'd on to the app, the environment variables were there, both the first push and second push.

Maybe I'm not reproducing your issue in a correct way, or maybe I'm misunderstanding the problem. Is this still an issue for you (now knowing that the environment variables do exist). Or can you help us with the reproduction? :) 

Thanks!

**Comment by bkrannich** [comment] 2019-02-22 09:57
Hi @kardolus,

Thank you very much for the follow-up!

`cf env` is showing all environment variables consistently as expected. However, as mentioned, at times (and I haven't really found a 100% pattern to provoke it and can only say that it happens 50% of all `cf push`es with `cflinuxfs3`) they are even missing from `/proc/<pid>/environ` (and thus also from `process.env`). Also, we have seen the issues with different buildpacks so it does not seem buildpack-specific.

For reproduction, it helps to uncomment/comment the commented lines in https://gist.github.com/bkrannich/d77681d7ea5caf1b52a0ffda4fcfb6ff#file-manifest-yml

Additionally, I could offer doing a joint session so that we can look at the system together.

Thanks in advance,
Bernd

**Comment by dfreilich** [comment] 2019-02-22 16:59
Hi @bkrannich, 

It's currently pretty high up in our [backlog](https://www.pivotaltracker.com/story/show/163972063), we'll investigate it again soon. Thanks!

**Comment by bkrannich** [comment] 2019-02-22 18:06
Hi @dfreilich,

Should I create another Github issue in the Cloud Controller repo?

Thanks in advance,
Bernd

**Comment by Zanadar** [comment] 2019-02-25 17:41
@bkrannich Yeah that'd be the best for you so you can track it there. Closing this issue on our end.

**Closed by Zanadar** 2019-02-25 17:41 UTC
Labels: scheduled

**Comment by bkrannich** [comment] 2019-02-26 08:27
Created https://github.com/cloudfoundry/cloud_controller_ng/issues/1298

**Comment by ericpromislow** [comment] 2019-04-12 22:56
Not a CAPI issue. The crux of the issue is that `cflinuxfs2` and `cflinuxfs3` install different versions of dash, and `cflinuxfs3:dash` drops the non-conforming env vars. Workaround: specify the command explicitly in the manifest (which was commented out).  And when you run `cf env APP` CAPI is querying its own database, not the app. Better to have an `/env` endpoint in your app and hit it to see what's really going on.

**Comment by tcdowney** [comment] 2019-04-29 23:28
@shanks3012 just want to confirm you've seen the investigation we did in https://github.com/cloudfoundry/cloud_controller_ng/issues/1298. This is a breaking change from the `cflinuxfs2` -> `cflinuxfs3` transition.
